/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Contents"
 * 	found in "/home/vagrant/magma/lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r15/s1ap-15.6.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -no-gen-example -fno-include-deps -D /home/vagrant/build/c/core/oai/tasks/s1ap/r15`
 */

#ifndef	_S1ap_E_RABToBeSetupItemCtxtSUReq_H_
#define	_S1ap_E_RABToBeSetupItemCtxtSUReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include "S1ap_E-RAB-ID.h"
#include "S1ap_E-RABLevelQoSParameters.h"
#include "S1ap_TransportLayerAddress.h"
#include "S1ap_GTP-TEID.h"
#include "S1ap_NAS-PDU.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct S1ap_ProtocolExtensionContainer;

/* S1ap_E-RABToBeSetupItemCtxtSUReq */
typedef struct S1ap_E_RABToBeSetupItemCtxtSUReq {
	S1ap_E_RAB_ID_t	 e_RAB_ID;
	S1ap_E_RABLevelQoSParameters_t	 e_RABlevelQoSParameters;
	S1ap_TransportLayerAddress_t	 transportLayerAddress;
	S1ap_GTP_TEID_t	 gTP_TEID;
	S1ap_NAS_PDU_t	*nAS_PDU;	/* OPTIONAL */
	struct S1ap_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1ap_E_RABToBeSetupItemCtxtSUReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1ap_E_RABToBeSetupItemCtxtSUReq;
extern asn_SEQUENCE_specifics_t asn_SPC_S1ap_E_RABToBeSetupItemCtxtSUReq_specs_1;
extern asn_TYPE_member_t asn_MBR_S1ap_E_RABToBeSetupItemCtxtSUReq_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _S1ap_E_RABToBeSetupItemCtxtSUReq_H_ */
#include <asn_internal.h>
