/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Descriptions"
 * 	found in "/home/vagrant/magma/lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r15/s1ap-15.6.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-example -fno-include-deps -D /home/vagrant/build/c/core/oai/tasks/s1ap/r15`
 */

#ifndef	_S1ap_SuccessfulOutcome_H_
#define	_S1ap_SuccessfulOutcome_H_


#include <asn_application.h>

/* Including external dependencies */
#include "S1ap_ProcedureCode.h"
#include "S1ap_Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "S1ap_HandoverRequired.h"
#include "S1ap_HandoverCommand.h"
#include "S1ap_HandoverPreparationFailure.h"
#include "S1ap_HandoverRequest.h"
#include "S1ap_HandoverRequestAcknowledge.h"
#include "S1ap_HandoverFailure.h"
#include "S1ap_PathSwitchRequest.h"
#include "S1ap_PathSwitchRequestAcknowledge.h"
#include "S1ap_PathSwitchRequestFailure.h"
#include "S1ap_E-RABSetupRequest.h"
#include "S1ap_E-RABSetupResponse.h"
#include "S1ap_E-RABModifyRequest.h"
#include "S1ap_E-RABModifyResponse.h"
#include "S1ap_E-RABReleaseCommand.h"
#include "S1ap_E-RABReleaseResponse.h"
#include "S1ap_InitialContextSetupRequest.h"
#include "S1ap_InitialContextSetupResponse.h"
#include "S1ap_InitialContextSetupFailure.h"
#include "S1ap_HandoverCancel.h"
#include "S1ap_HandoverCancelAcknowledge.h"
#include "S1ap_KillRequest.h"
#include "S1ap_KillResponse.h"
#include "S1ap_Reset.h"
#include "S1ap_ResetAcknowledge.h"
#include "S1ap_S1SetupRequest.h"
#include "S1ap_S1SetupResponse.h"
#include "S1ap_S1SetupFailure.h"
#include "S1ap_UEContextModificationRequest.h"
#include "S1ap_UEContextModificationResponse.h"
#include "S1ap_UEContextModificationFailure.h"
#include "S1ap_UEContextReleaseCommand.h"
#include "S1ap_UEContextReleaseComplete.h"
#include "S1ap_ENBConfigurationUpdate.h"
#include "S1ap_ENBConfigurationUpdateAcknowledge.h"
#include "S1ap_ENBConfigurationUpdateFailure.h"
#include "S1ap_MMEConfigurationUpdate.h"
#include "S1ap_MMEConfigurationUpdateAcknowledge.h"
#include "S1ap_MMEConfigurationUpdateFailure.h"
#include "S1ap_WriteReplaceWarningRequest.h"
#include "S1ap_WriteReplaceWarningResponse.h"
#include "S1ap_UERadioCapabilityMatchRequest.h"
#include "S1ap_UERadioCapabilityMatchResponse.h"
#include "S1ap_E-RABModificationIndication.h"
#include "S1ap_E-RABModificationConfirm.h"
#include "S1ap_UEContextModificationIndication.h"
#include "S1ap_UEContextModificationConfirm.h"
#include "S1ap_UEContextSuspendRequest.h"
#include "S1ap_UEContextSuspendResponse.h"
#include "S1ap_UEContextResumeRequest.h"
#include "S1ap_UEContextResumeResponse.h"
#include "S1ap_UEContextResumeFailure.h"
#include "S1ap_HandoverNotify.h"
#include "S1ap_E-RABReleaseIndication.h"
#include "S1ap_Paging.h"
#include "S1ap_DownlinkNASTransport.h"
#include "S1ap_InitialUEMessage.h"
#include "S1ap_UplinkNASTransport.h"
#include "S1ap_ErrorIndication.h"
#include "S1ap_NASNonDeliveryIndication.h"
#include "S1ap_UEContextReleaseRequest.h"
#include "S1ap_DownlinkS1cdma2000tunnelling.h"
#include "S1ap_UplinkS1cdma2000tunnelling.h"
#include "S1ap_UECapabilityInfoIndication.h"
#include "S1ap_ENBStatusTransfer.h"
#include "S1ap_MMEStatusTransfer.h"
#include "S1ap_DeactivateTrace.h"
#include "S1ap_TraceStart.h"
#include "S1ap_TraceFailureIndication.h"
#include "S1ap_CellTrafficTrace.h"
#include "S1ap_LocationReportingControl.h"
#include "S1ap_LocationReportingFailureIndication.h"
#include "S1ap_LocationReport.h"
#include "S1ap_OverloadStart.h"
#include "S1ap_OverloadStop.h"
#include "S1ap_ENBDirectInformationTransfer.h"
#include "S1ap_MMEDirectInformationTransfer.h"
#include "S1ap_ENBConfigurationTransfer.h"
#include "S1ap_MMEConfigurationTransfer.h"
#include "S1ap_PrivateMessage.h"
#include "S1ap_DownlinkUEAssociatedLPPaTransport.h"
#include "S1ap_UplinkUEAssociatedLPPaTransport.h"
#include "S1ap_DownlinkNonUEAssociatedLPPaTransport.h"
#include "S1ap_UplinkNonUEAssociatedLPPaTransport.h"
#include "S1ap_PWSRestartIndication.h"
#include "S1ap_RerouteNASRequest.h"
#include "S1ap_PWSFailureIndication.h"
#include "S1ap_ConnectionEstablishmentIndication.h"
#include "S1ap_NASDeliveryIndication.h"
#include "S1ap_RetrieveUEInformation.h"
#include "S1ap_UEInformationTransfer.h"
#include "S1ap_ENBCPRelocationIndication.h"
#include "S1ap_MMECPRelocationIndication.h"
#include "S1ap_SecondaryRATDataUsageReport.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum S1ap_SuccessfulOutcome__value_PR {
	S1ap_SuccessfulOutcome__value_PR_NOTHING,	/* No components present */
	S1ap_SuccessfulOutcome__value_PR_HandoverCommand,
	S1ap_SuccessfulOutcome__value_PR_HandoverRequestAcknowledge,
	S1ap_SuccessfulOutcome__value_PR_PathSwitchRequestAcknowledge,
	S1ap_SuccessfulOutcome__value_PR_E_RABSetupResponse,
	S1ap_SuccessfulOutcome__value_PR_E_RABModifyResponse,
	S1ap_SuccessfulOutcome__value_PR_E_RABReleaseResponse,
	S1ap_SuccessfulOutcome__value_PR_InitialContextSetupResponse,
	S1ap_SuccessfulOutcome__value_PR_HandoverCancelAcknowledge,
	S1ap_SuccessfulOutcome__value_PR_KillResponse,
	S1ap_SuccessfulOutcome__value_PR_ResetAcknowledge,
	S1ap_SuccessfulOutcome__value_PR_S1SetupResponse,
	S1ap_SuccessfulOutcome__value_PR_UEContextModificationResponse,
	S1ap_SuccessfulOutcome__value_PR_UEContextReleaseComplete,
	S1ap_SuccessfulOutcome__value_PR_ENBConfigurationUpdateAcknowledge,
	S1ap_SuccessfulOutcome__value_PR_MMEConfigurationUpdateAcknowledge,
	S1ap_SuccessfulOutcome__value_PR_WriteReplaceWarningResponse,
	S1ap_SuccessfulOutcome__value_PR_UERadioCapabilityMatchResponse,
	S1ap_SuccessfulOutcome__value_PR_E_RABModificationConfirm,
	S1ap_SuccessfulOutcome__value_PR_UEContextModificationConfirm,
	S1ap_SuccessfulOutcome__value_PR_UEContextSuspendResponse,
	S1ap_SuccessfulOutcome__value_PR_UEContextResumeResponse
} S1ap_SuccessfulOutcome__value_PR;

/* S1ap_SuccessfulOutcome */
typedef struct S1ap_SuccessfulOutcome {
	S1ap_ProcedureCode_t	 procedureCode;
	S1ap_Criticality_t	 criticality;
	struct S1ap_SuccessfulOutcome__value {
		S1ap_SuccessfulOutcome__value_PR present;
		union S1ap_SuccessfulOutcome__S1ap_value_u {
			S1ap_HandoverCommand_t	 HandoverCommand;
			S1ap_HandoverRequestAcknowledge_t	 HandoverRequestAcknowledge;
			S1ap_PathSwitchRequestAcknowledge_t	 PathSwitchRequestAcknowledge;
			S1ap_E_RABSetupResponse_t	 E_RABSetupResponse;
			S1ap_E_RABModifyResponse_t	 E_RABModifyResponse;
			S1ap_E_RABReleaseResponse_t	 E_RABReleaseResponse;
			S1ap_InitialContextSetupResponse_t	 InitialContextSetupResponse;
			S1ap_HandoverCancelAcknowledge_t	 HandoverCancelAcknowledge;
			S1ap_KillResponse_t	 KillResponse;
			S1ap_ResetAcknowledge_t	 ResetAcknowledge;
			S1ap_S1SetupResponse_t	 S1SetupResponse;
			S1ap_UEContextModificationResponse_t	 UEContextModificationResponse;
			S1ap_UEContextReleaseComplete_t	 UEContextReleaseComplete;
			S1ap_ENBConfigurationUpdateAcknowledge_t	 ENBConfigurationUpdateAcknowledge;
			S1ap_MMEConfigurationUpdateAcknowledge_t	 MMEConfigurationUpdateAcknowledge;
			S1ap_WriteReplaceWarningResponse_t	 WriteReplaceWarningResponse;
			S1ap_UERadioCapabilityMatchResponse_t	 UERadioCapabilityMatchResponse;
			S1ap_E_RABModificationConfirm_t	 E_RABModificationConfirm;
			S1ap_UEContextModificationConfirm_t	 UEContextModificationConfirm;
			S1ap_UEContextSuspendResponse_t	 UEContextSuspendResponse;
			S1ap_UEContextResumeResponse_t	 UEContextResumeResponse;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1ap_SuccessfulOutcome_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1ap_SuccessfulOutcome;
extern asn_SEQUENCE_specifics_t asn_SPC_S1ap_SuccessfulOutcome_specs_1;
extern asn_TYPE_member_t asn_MBR_S1ap_SuccessfulOutcome_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _S1ap_SuccessfulOutcome_H_ */
#include <asn_internal.h>
