/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Descriptions"
 * 	found in "/home/vagrant/magma/lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r15/s1ap-15.6.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-example -fno-include-deps -D /home/vagrant/build/c/core/oai/tasks/s1ap/r15`
 */

#ifndef	_S1ap_InitiatingMessage_H_
#define	_S1ap_InitiatingMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "S1ap_ProcedureCode.h"
#include "S1ap_Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "S1ap_HandoverRequired.h"
#include "S1ap_HandoverCommand.h"
#include "S1ap_HandoverPreparationFailure.h"
#include "S1ap_HandoverRequest.h"
#include "S1ap_HandoverRequestAcknowledge.h"
#include "S1ap_HandoverFailure.h"
#include "S1ap_PathSwitchRequest.h"
#include "S1ap_PathSwitchRequestAcknowledge.h"
#include "S1ap_PathSwitchRequestFailure.h"
#include "S1ap_E-RABSetupRequest.h"
#include "S1ap_E-RABSetupResponse.h"
#include "S1ap_E-RABModifyRequest.h"
#include "S1ap_E-RABModifyResponse.h"
#include "S1ap_E-RABReleaseCommand.h"
#include "S1ap_E-RABReleaseResponse.h"
#include "S1ap_InitialContextSetupRequest.h"
#include "S1ap_InitialContextSetupResponse.h"
#include "S1ap_InitialContextSetupFailure.h"
#include "S1ap_HandoverCancel.h"
#include "S1ap_HandoverCancelAcknowledge.h"
#include "S1ap_KillRequest.h"
#include "S1ap_KillResponse.h"
#include "S1ap_Reset.h"
#include "S1ap_ResetAcknowledge.h"
#include "S1ap_S1SetupRequest.h"
#include "S1ap_S1SetupResponse.h"
#include "S1ap_S1SetupFailure.h"
#include "S1ap_UEContextModificationRequest.h"
#include "S1ap_UEContextModificationResponse.h"
#include "S1ap_UEContextModificationFailure.h"
#include "S1ap_UEContextReleaseCommand.h"
#include "S1ap_UEContextReleaseComplete.h"
#include "S1ap_ENBConfigurationUpdate.h"
#include "S1ap_ENBConfigurationUpdateAcknowledge.h"
#include "S1ap_ENBConfigurationUpdateFailure.h"
#include "S1ap_MMEConfigurationUpdate.h"
#include "S1ap_MMEConfigurationUpdateAcknowledge.h"
#include "S1ap_MMEConfigurationUpdateFailure.h"
#include "S1ap_WriteReplaceWarningRequest.h"
#include "S1ap_WriteReplaceWarningResponse.h"
#include "S1ap_UERadioCapabilityMatchRequest.h"
#include "S1ap_UERadioCapabilityMatchResponse.h"
#include "S1ap_E-RABModificationIndication.h"
#include "S1ap_E-RABModificationConfirm.h"
#include "S1ap_UEContextModificationIndication.h"
#include "S1ap_UEContextModificationConfirm.h"
#include "S1ap_UEContextSuspendRequest.h"
#include "S1ap_UEContextSuspendResponse.h"
#include "S1ap_UEContextResumeRequest.h"
#include "S1ap_UEContextResumeResponse.h"
#include "S1ap_UEContextResumeFailure.h"
#include "S1ap_HandoverNotify.h"
#include "S1ap_E-RABReleaseIndication.h"
#include "S1ap_Paging.h"
#include "S1ap_DownlinkNASTransport.h"
#include "S1ap_InitialUEMessage.h"
#include "S1ap_UplinkNASTransport.h"
#include "S1ap_ErrorIndication.h"
#include "S1ap_NASNonDeliveryIndication.h"
#include "S1ap_UEContextReleaseRequest.h"
#include "S1ap_DownlinkS1cdma2000tunnelling.h"
#include "S1ap_UplinkS1cdma2000tunnelling.h"
#include "S1ap_UECapabilityInfoIndication.h"
#include "S1ap_ENBStatusTransfer.h"
#include "S1ap_MMEStatusTransfer.h"
#include "S1ap_DeactivateTrace.h"
#include "S1ap_TraceStart.h"
#include "S1ap_TraceFailureIndication.h"
#include "S1ap_CellTrafficTrace.h"
#include "S1ap_LocationReportingControl.h"
#include "S1ap_LocationReportingFailureIndication.h"
#include "S1ap_LocationReport.h"
#include "S1ap_OverloadStart.h"
#include "S1ap_OverloadStop.h"
#include "S1ap_ENBDirectInformationTransfer.h"
#include "S1ap_MMEDirectInformationTransfer.h"
#include "S1ap_ENBConfigurationTransfer.h"
#include "S1ap_MMEConfigurationTransfer.h"
#include "S1ap_PrivateMessage.h"
#include "S1ap_DownlinkUEAssociatedLPPaTransport.h"
#include "S1ap_UplinkUEAssociatedLPPaTransport.h"
#include "S1ap_DownlinkNonUEAssociatedLPPaTransport.h"
#include "S1ap_UplinkNonUEAssociatedLPPaTransport.h"
#include "S1ap_PWSRestartIndication.h"
#include "S1ap_RerouteNASRequest.h"
#include "S1ap_PWSFailureIndication.h"
#include "S1ap_ConnectionEstablishmentIndication.h"
#include "S1ap_NASDeliveryIndication.h"
#include "S1ap_RetrieveUEInformation.h"
#include "S1ap_UEInformationTransfer.h"
#include "S1ap_ENBCPRelocationIndication.h"
#include "S1ap_MMECPRelocationIndication.h"
#include "S1ap_SecondaryRATDataUsageReport.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum S1ap_InitiatingMessage__value_PR {
	S1ap_InitiatingMessage__value_PR_NOTHING,	/* No components present */
	S1ap_InitiatingMessage__value_PR_HandoverRequired,
	S1ap_InitiatingMessage__value_PR_HandoverRequest,
	S1ap_InitiatingMessage__value_PR_PathSwitchRequest,
	S1ap_InitiatingMessage__value_PR_E_RABSetupRequest,
	S1ap_InitiatingMessage__value_PR_E_RABModifyRequest,
	S1ap_InitiatingMessage__value_PR_E_RABReleaseCommand,
	S1ap_InitiatingMessage__value_PR_InitialContextSetupRequest,
	S1ap_InitiatingMessage__value_PR_HandoverCancel,
	S1ap_InitiatingMessage__value_PR_KillRequest,
	S1ap_InitiatingMessage__value_PR_Reset,
	S1ap_InitiatingMessage__value_PR_S1SetupRequest,
	S1ap_InitiatingMessage__value_PR_UEContextModificationRequest,
	S1ap_InitiatingMessage__value_PR_UEContextReleaseCommand,
	S1ap_InitiatingMessage__value_PR_ENBConfigurationUpdate,
	S1ap_InitiatingMessage__value_PR_MMEConfigurationUpdate,
	S1ap_InitiatingMessage__value_PR_WriteReplaceWarningRequest,
	S1ap_InitiatingMessage__value_PR_UERadioCapabilityMatchRequest,
	S1ap_InitiatingMessage__value_PR_E_RABModificationIndication,
	S1ap_InitiatingMessage__value_PR_UEContextModificationIndication,
	S1ap_InitiatingMessage__value_PR_UEContextSuspendRequest,
	S1ap_InitiatingMessage__value_PR_UEContextResumeRequest,
	S1ap_InitiatingMessage__value_PR_HandoverNotify,
	S1ap_InitiatingMessage__value_PR_E_RABReleaseIndication,
	S1ap_InitiatingMessage__value_PR_Paging,
	S1ap_InitiatingMessage__value_PR_DownlinkNASTransport,
	S1ap_InitiatingMessage__value_PR_InitialUEMessage,
	S1ap_InitiatingMessage__value_PR_UplinkNASTransport,
	S1ap_InitiatingMessage__value_PR_ErrorIndication,
	S1ap_InitiatingMessage__value_PR_NASNonDeliveryIndication,
	S1ap_InitiatingMessage__value_PR_UEContextReleaseRequest,
	S1ap_InitiatingMessage__value_PR_DownlinkS1cdma2000tunnelling,
	S1ap_InitiatingMessage__value_PR_UplinkS1cdma2000tunnelling,
	S1ap_InitiatingMessage__value_PR_UECapabilityInfoIndication,
	S1ap_InitiatingMessage__value_PR_ENBStatusTransfer,
	S1ap_InitiatingMessage__value_PR_MMEStatusTransfer,
	S1ap_InitiatingMessage__value_PR_DeactivateTrace,
	S1ap_InitiatingMessage__value_PR_TraceStart,
	S1ap_InitiatingMessage__value_PR_TraceFailureIndication,
	S1ap_InitiatingMessage__value_PR_CellTrafficTrace,
	S1ap_InitiatingMessage__value_PR_LocationReportingControl,
	S1ap_InitiatingMessage__value_PR_LocationReportingFailureIndication,
	S1ap_InitiatingMessage__value_PR_LocationReport,
	S1ap_InitiatingMessage__value_PR_OverloadStart,
	S1ap_InitiatingMessage__value_PR_OverloadStop,
	S1ap_InitiatingMessage__value_PR_ENBDirectInformationTransfer,
	S1ap_InitiatingMessage__value_PR_MMEDirectInformationTransfer,
	S1ap_InitiatingMessage__value_PR_ENBConfigurationTransfer,
	S1ap_InitiatingMessage__value_PR_MMEConfigurationTransfer,
	S1ap_InitiatingMessage__value_PR_PrivateMessage,
	S1ap_InitiatingMessage__value_PR_DownlinkUEAssociatedLPPaTransport,
	S1ap_InitiatingMessage__value_PR_UplinkUEAssociatedLPPaTransport,
	S1ap_InitiatingMessage__value_PR_DownlinkNonUEAssociatedLPPaTransport,
	S1ap_InitiatingMessage__value_PR_UplinkNonUEAssociatedLPPaTransport,
	S1ap_InitiatingMessage__value_PR_PWSRestartIndication,
	S1ap_InitiatingMessage__value_PR_RerouteNASRequest,
	S1ap_InitiatingMessage__value_PR_PWSFailureIndication,
	S1ap_InitiatingMessage__value_PR_ConnectionEstablishmentIndication,
	S1ap_InitiatingMessage__value_PR_NASDeliveryIndication,
	S1ap_InitiatingMessage__value_PR_RetrieveUEInformation,
	S1ap_InitiatingMessage__value_PR_UEInformationTransfer,
	S1ap_InitiatingMessage__value_PR_ENBCPRelocationIndication,
	S1ap_InitiatingMessage__value_PR_MMECPRelocationIndication,
	S1ap_InitiatingMessage__value_PR_SecondaryRATDataUsageReport
} S1ap_InitiatingMessage__value_PR;

/* S1ap_InitiatingMessage */
typedef struct S1ap_InitiatingMessage {
	S1ap_ProcedureCode_t	 procedureCode;
	S1ap_Criticality_t	 criticality;
	struct S1ap_InitiatingMessage__value {
		S1ap_InitiatingMessage__value_PR present;
		union S1ap_InitiatingMessage__S1ap_value_u {
			S1ap_HandoverRequired_t	 HandoverRequired;
			S1ap_HandoverRequest_t	 HandoverRequest;
			S1ap_PathSwitchRequest_t	 PathSwitchRequest;
			S1ap_E_RABSetupRequest_t	 E_RABSetupRequest;
			S1ap_E_RABModifyRequest_t	 E_RABModifyRequest;
			S1ap_E_RABReleaseCommand_t	 E_RABReleaseCommand;
			S1ap_InitialContextSetupRequest_t	 InitialContextSetupRequest;
			S1ap_HandoverCancel_t	 HandoverCancel;
			S1ap_KillRequest_t	 KillRequest;
			S1ap_Reset_t	 Reset;
			S1ap_S1SetupRequest_t	 S1SetupRequest;
			S1ap_UEContextModificationRequest_t	 UEContextModificationRequest;
			S1ap_UEContextReleaseCommand_t	 UEContextReleaseCommand;
			S1ap_ENBConfigurationUpdate_t	 ENBConfigurationUpdate;
			S1ap_MMEConfigurationUpdate_t	 MMEConfigurationUpdate;
			S1ap_WriteReplaceWarningRequest_t	 WriteReplaceWarningRequest;
			S1ap_UERadioCapabilityMatchRequest_t	 UERadioCapabilityMatchRequest;
			S1ap_E_RABModificationIndication_t	 E_RABModificationIndication;
			S1ap_UEContextModificationIndication_t	 UEContextModificationIndication;
			S1ap_UEContextSuspendRequest_t	 UEContextSuspendRequest;
			S1ap_UEContextResumeRequest_t	 UEContextResumeRequest;
			S1ap_HandoverNotify_t	 HandoverNotify;
			S1ap_E_RABReleaseIndication_t	 E_RABReleaseIndication;
			S1ap_Paging_t	 Paging;
			S1ap_DownlinkNASTransport_t	 DownlinkNASTransport;
			S1ap_InitialUEMessage_t	 InitialUEMessage;
			S1ap_UplinkNASTransport_t	 UplinkNASTransport;
			S1ap_ErrorIndication_t	 ErrorIndication;
			S1ap_NASNonDeliveryIndication_t	 NASNonDeliveryIndication;
			S1ap_UEContextReleaseRequest_t	 UEContextReleaseRequest;
			S1ap_DownlinkS1cdma2000tunnelling_t	 DownlinkS1cdma2000tunnelling;
			S1ap_UplinkS1cdma2000tunnelling_t	 UplinkS1cdma2000tunnelling;
			S1ap_UECapabilityInfoIndication_t	 UECapabilityInfoIndication;
			S1ap_ENBStatusTransfer_t	 ENBStatusTransfer;
			S1ap_MMEStatusTransfer_t	 MMEStatusTransfer;
			S1ap_DeactivateTrace_t	 DeactivateTrace;
			S1ap_TraceStart_t	 TraceStart;
			S1ap_TraceFailureIndication_t	 TraceFailureIndication;
			S1ap_CellTrafficTrace_t	 CellTrafficTrace;
			S1ap_LocationReportingControl_t	 LocationReportingControl;
			S1ap_LocationReportingFailureIndication_t	 LocationReportingFailureIndication;
			S1ap_LocationReport_t	 LocationReport;
			S1ap_OverloadStart_t	 OverloadStart;
			S1ap_OverloadStop_t	 OverloadStop;
			S1ap_ENBDirectInformationTransfer_t	 ENBDirectInformationTransfer;
			S1ap_MMEDirectInformationTransfer_t	 MMEDirectInformationTransfer;
			S1ap_ENBConfigurationTransfer_t	 ENBConfigurationTransfer;
			S1ap_MMEConfigurationTransfer_t	 MMEConfigurationTransfer;
			S1ap_PrivateMessage_t	 PrivateMessage;
			S1ap_DownlinkUEAssociatedLPPaTransport_t	 DownlinkUEAssociatedLPPaTransport;
			S1ap_UplinkUEAssociatedLPPaTransport_t	 UplinkUEAssociatedLPPaTransport;
			S1ap_DownlinkNonUEAssociatedLPPaTransport_t	 DownlinkNonUEAssociatedLPPaTransport;
			S1ap_UplinkNonUEAssociatedLPPaTransport_t	 UplinkNonUEAssociatedLPPaTransport;
			S1ap_PWSRestartIndication_t	 PWSRestartIndication;
			S1ap_RerouteNASRequest_t	 RerouteNASRequest;
			S1ap_PWSFailureIndication_t	 PWSFailureIndication;
			S1ap_ConnectionEstablishmentIndication_t	 ConnectionEstablishmentIndication;
			S1ap_NASDeliveryIndication_t	 NASDeliveryIndication;
			S1ap_RetrieveUEInformation_t	 RetrieveUEInformation;
			S1ap_UEInformationTransfer_t	 UEInformationTransfer;
			S1ap_ENBCPRelocationIndication_t	 ENBCPRelocationIndication;
			S1ap_MMECPRelocationIndication_t	 MMECPRelocationIndication;
			S1ap_SecondaryRATDataUsageReport_t	 SecondaryRATDataUsageReport;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1ap_InitiatingMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1ap_InitiatingMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_S1ap_InitiatingMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_S1ap_InitiatingMessage_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _S1ap_InitiatingMessage_H_ */
#include <asn_internal.h>
