/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Descriptions"
 * 	found in "/home/vagrant/magma/lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r15/s1ap-15.6.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-example -fno-include-deps -D /home/vagrant/build/c/core/oai/tasks/s1ap/r15`
 */

#include "S1ap_SuccessfulOutcome.h"

static const long asn_VAL_1_S1ap_id_HandoverPreparation = 0;
static const long asn_VAL_1_S1ap_reject = 0;
static const long asn_VAL_2_S1ap_id_HandoverResourceAllocation = 1;
static const long asn_VAL_2_S1ap_reject = 0;
static const long asn_VAL_3_S1ap_id_PathSwitchRequest = 3;
static const long asn_VAL_3_S1ap_reject = 0;
static const long asn_VAL_4_S1ap_id_E_RABSetup = 5;
static const long asn_VAL_4_S1ap_reject = 0;
static const long asn_VAL_5_S1ap_id_E_RABModify = 6;
static const long asn_VAL_5_S1ap_reject = 0;
static const long asn_VAL_6_S1ap_id_E_RABRelease = 7;
static const long asn_VAL_6_S1ap_reject = 0;
static const long asn_VAL_7_S1ap_id_InitialContextSetup = 9;
static const long asn_VAL_7_S1ap_reject = 0;
static const long asn_VAL_8_S1ap_id_HandoverCancel = 4;
static const long asn_VAL_8_S1ap_reject = 0;
static const long asn_VAL_9_S1ap_id_Kill = 43;
static const long asn_VAL_9_S1ap_reject = 0;
static const long asn_VAL_10_S1ap_id_Reset = 14;
static const long asn_VAL_10_S1ap_reject = 0;
static const long asn_VAL_11_S1ap_id_S1Setup = 17;
static const long asn_VAL_11_S1ap_reject = 0;
static const long asn_VAL_12_S1ap_id_UEContextModification = 21;
static const long asn_VAL_12_S1ap_reject = 0;
static const long asn_VAL_13_S1ap_id_UEContextRelease = 23;
static const long asn_VAL_13_S1ap_reject = 0;
static const long asn_VAL_14_S1ap_id_ENBConfigurationUpdate = 29;
static const long asn_VAL_14_S1ap_reject = 0;
static const long asn_VAL_15_S1ap_id_MMEConfigurationUpdate = 30;
static const long asn_VAL_15_S1ap_reject = 0;
static const long asn_VAL_16_S1ap_id_WriteReplaceWarning = 36;
static const long asn_VAL_16_S1ap_reject = 0;
static const long asn_VAL_17_S1ap_id_UERadioCapabilityMatch = 48;
static const long asn_VAL_17_S1ap_reject = 0;
static const long asn_VAL_18_S1ap_id_E_RABModificationIndication = 50;
static const long asn_VAL_18_S1ap_reject = 0;
static const long asn_VAL_19_S1ap_id_UEContextModificationIndication = 53;
static const long asn_VAL_19_S1ap_reject = 0;
static const long asn_VAL_20_S1ap_id_UEContextSuspend = 55;
static const long asn_VAL_20_S1ap_reject = 0;
static const long asn_VAL_21_S1ap_id_UEContextResume = 56;
static const long asn_VAL_21_S1ap_reject = 0;
static const long asn_VAL_22_S1ap_id_HandoverNotification = 2;
static const long asn_VAL_22_S1ap_ignore = 1;
static const long asn_VAL_23_S1ap_id_E_RABReleaseIndication = 8;
static const long asn_VAL_23_S1ap_ignore = 1;
static const long asn_VAL_24_S1ap_id_Paging = 10;
static const long asn_VAL_24_S1ap_ignore = 1;
static const long asn_VAL_25_S1ap_id_downlinkNASTransport = 11;
static const long asn_VAL_25_S1ap_ignore = 1;
static const long asn_VAL_26_S1ap_id_initialUEMessage = 12;
static const long asn_VAL_26_S1ap_ignore = 1;
static const long asn_VAL_27_S1ap_id_uplinkNASTransport = 13;
static const long asn_VAL_27_S1ap_ignore = 1;
static const long asn_VAL_28_S1ap_id_ErrorIndication = 15;
static const long asn_VAL_28_S1ap_ignore = 1;
static const long asn_VAL_29_S1ap_id_NASNonDeliveryIndication = 16;
static const long asn_VAL_29_S1ap_ignore = 1;
static const long asn_VAL_30_S1ap_id_UEContextReleaseRequest = 18;
static const long asn_VAL_30_S1ap_ignore = 1;
static const long asn_VAL_31_S1ap_id_DownlinkS1cdma2000tunnelling = 19;
static const long asn_VAL_31_S1ap_ignore = 1;
static const long asn_VAL_32_S1ap_id_UplinkS1cdma2000tunnelling = 20;
static const long asn_VAL_32_S1ap_ignore = 1;
static const long asn_VAL_33_S1ap_id_UECapabilityInfoIndication = 22;
static const long asn_VAL_33_S1ap_ignore = 1;
static const long asn_VAL_34_S1ap_id_eNBStatusTransfer = 24;
static const long asn_VAL_34_S1ap_ignore = 1;
static const long asn_VAL_35_S1ap_id_MMEStatusTransfer = 25;
static const long asn_VAL_35_S1ap_ignore = 1;
static const long asn_VAL_36_S1ap_id_DeactivateTrace = 26;
static const long asn_VAL_36_S1ap_ignore = 1;
static const long asn_VAL_37_S1ap_id_TraceStart = 27;
static const long asn_VAL_37_S1ap_ignore = 1;
static const long asn_VAL_38_S1ap_id_TraceFailureIndication = 28;
static const long asn_VAL_38_S1ap_ignore = 1;
static const long asn_VAL_39_S1ap_id_CellTrafficTrace = 42;
static const long asn_VAL_39_S1ap_ignore = 1;
static const long asn_VAL_40_S1ap_id_LocationReportingControl = 31;
static const long asn_VAL_40_S1ap_ignore = 1;
static const long asn_VAL_41_S1ap_id_LocationReportingFailureIndication = 32;
static const long asn_VAL_41_S1ap_ignore = 1;
static const long asn_VAL_42_S1ap_id_LocationReport = 33;
static const long asn_VAL_42_S1ap_ignore = 1;
static const long asn_VAL_43_S1ap_id_OverloadStart = 34;
static const long asn_VAL_43_S1ap_ignore = 1;
static const long asn_VAL_44_S1ap_id_OverloadStop = 35;
static const long asn_VAL_44_S1ap_reject = 0;
static const long asn_VAL_45_S1ap_id_eNBDirectInformationTransfer = 37;
static const long asn_VAL_45_S1ap_ignore = 1;
static const long asn_VAL_46_S1ap_id_MMEDirectInformationTransfer = 38;
static const long asn_VAL_46_S1ap_ignore = 1;
static const long asn_VAL_47_S1ap_id_eNBConfigurationTransfer = 40;
static const long asn_VAL_47_S1ap_ignore = 1;
static const long asn_VAL_48_S1ap_id_MMEConfigurationTransfer = 41;
static const long asn_VAL_48_S1ap_ignore = 1;
static const long asn_VAL_49_S1ap_id_PrivateMessage = 39;
static const long asn_VAL_49_S1ap_ignore = 1;
static const long asn_VAL_50_S1ap_id_downlinkUEAssociatedLPPaTransport = 44;
static const long asn_VAL_50_S1ap_ignore = 1;
static const long asn_VAL_51_S1ap_id_uplinkUEAssociatedLPPaTransport = 45;
static const long asn_VAL_51_S1ap_ignore = 1;
static const long asn_VAL_52_S1ap_id_downlinkNonUEAssociatedLPPaTransport = 46;
static const long asn_VAL_52_S1ap_ignore = 1;
static const long asn_VAL_53_S1ap_id_uplinkNonUEAssociatedLPPaTransport = 47;
static const long asn_VAL_53_S1ap_ignore = 1;
static const long asn_VAL_54_S1ap_id_PWSRestartIndication = 49;
static const long asn_VAL_54_S1ap_ignore = 1;
static const long asn_VAL_55_S1ap_id_RerouteNASRequest = 52;
static const long asn_VAL_55_S1ap_reject = 0;
static const long asn_VAL_56_S1ap_id_PWSFailureIndication = 51;
static const long asn_VAL_56_S1ap_ignore = 1;
static const long asn_VAL_57_S1ap_id_ConnectionEstablishmentIndication = 54;
static const long asn_VAL_57_S1ap_reject = 0;
static const long asn_VAL_58_S1ap_id_NASDeliveryIndication = 57;
static const long asn_VAL_58_S1ap_ignore = 1;
static const long asn_VAL_59_S1ap_id_RetrieveUEInformation = 58;
static const long asn_VAL_59_S1ap_reject = 0;
static const long asn_VAL_60_S1ap_id_UEInformationTransfer = 59;
static const long asn_VAL_60_S1ap_reject = 0;
static const long asn_VAL_61_S1ap_id_eNBCPRelocationIndication = 60;
static const long asn_VAL_61_S1ap_reject = 0;
static const long asn_VAL_62_S1ap_id_MMECPRelocationIndication = 61;
static const long asn_VAL_62_S1ap_reject = 0;
static const long asn_VAL_63_S1ap_id_SecondaryRATDataUsageReport = 62;
static const long asn_VAL_63_S1ap_ignore = 1;
static const asn_ioc_cell_t asn_IOS_S1ap_S1AP_ELEMENTARY_PROCEDURES_1_rows[] = {
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_HandoverRequired },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_HandoverCommand },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_S1ap_HandoverPreparationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_1_S1ap_id_HandoverPreparation },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_1_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_HandoverRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_HandoverRequestAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_S1ap_HandoverFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_2_S1ap_id_HandoverResourceAllocation },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_2_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_PathSwitchRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_PathSwitchRequestAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_S1ap_PathSwitchRequestFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_3_S1ap_id_PathSwitchRequest },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_3_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_E_RABSetupRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_E_RABSetupResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_4_S1ap_id_E_RABSetup },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_4_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_E_RABModifyRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_E_RABModifyResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_5_S1ap_id_E_RABModify },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_5_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_E_RABReleaseCommand },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_E_RABReleaseResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_6_S1ap_id_E_RABRelease },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_6_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_InitialContextSetupRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_InitialContextSetupResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_S1ap_InitialContextSetupFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_7_S1ap_id_InitialContextSetup },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_7_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_HandoverCancel },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_HandoverCancelAcknowledge },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_8_S1ap_id_HandoverCancel },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_8_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_KillRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_KillResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_9_S1ap_id_Kill },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_9_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_Reset },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_ResetAcknowledge },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_10_S1ap_id_Reset },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_10_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_S1SetupRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_S1SetupResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_S1ap_S1SetupFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_11_S1ap_id_S1Setup },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_11_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_UEContextModificationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_UEContextModificationResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_S1ap_UEContextModificationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_12_S1ap_id_UEContextModification },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_12_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_UEContextReleaseCommand },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_UEContextReleaseComplete },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_13_S1ap_id_UEContextRelease },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_13_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_ENBConfigurationUpdate },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_ENBConfigurationUpdateAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_S1ap_ENBConfigurationUpdateFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_14_S1ap_id_ENBConfigurationUpdate },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_14_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_MMEConfigurationUpdate },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_MMEConfigurationUpdateAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_S1ap_MMEConfigurationUpdateFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_15_S1ap_id_MMEConfigurationUpdate },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_15_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_WriteReplaceWarningRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_WriteReplaceWarningResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_16_S1ap_id_WriteReplaceWarning },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_16_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_UERadioCapabilityMatchRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_UERadioCapabilityMatchResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_17_S1ap_id_UERadioCapabilityMatch },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_17_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_E_RABModificationIndication },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_E_RABModificationConfirm },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_18_S1ap_id_E_RABModificationIndication },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_18_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_UEContextModificationIndication },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_UEContextModificationConfirm },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_19_S1ap_id_UEContextModificationIndication },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_19_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_UEContextSuspendRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_UEContextSuspendResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_20_S1ap_id_UEContextSuspend },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_20_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_UEContextResumeRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_S1ap_UEContextResumeResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_S1ap_UEContextResumeFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_21_S1ap_id_UEContextResume },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_21_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_HandoverNotify },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_22_S1ap_id_HandoverNotification },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_22_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_E_RABReleaseIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_23_S1ap_id_E_RABReleaseIndication },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_23_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_Paging },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_24_S1ap_id_Paging },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_24_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_DownlinkNASTransport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_25_S1ap_id_downlinkNASTransport },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_25_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_InitialUEMessage },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_26_S1ap_id_initialUEMessage },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_26_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_UplinkNASTransport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_27_S1ap_id_uplinkNASTransport },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_27_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_ErrorIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_28_S1ap_id_ErrorIndication },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_28_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_NASNonDeliveryIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_29_S1ap_id_NASNonDeliveryIndication },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_29_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_UEContextReleaseRequest },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_30_S1ap_id_UEContextReleaseRequest },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_30_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_DownlinkS1cdma2000tunnelling },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_31_S1ap_id_DownlinkS1cdma2000tunnelling },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_31_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_UplinkS1cdma2000tunnelling },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_32_S1ap_id_UplinkS1cdma2000tunnelling },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_32_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_UECapabilityInfoIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_33_S1ap_id_UECapabilityInfoIndication },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_33_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_ENBStatusTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_34_S1ap_id_eNBStatusTransfer },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_34_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_MMEStatusTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_35_S1ap_id_MMEStatusTransfer },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_35_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_DeactivateTrace },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_36_S1ap_id_DeactivateTrace },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_36_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_TraceStart },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_37_S1ap_id_TraceStart },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_37_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_TraceFailureIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_38_S1ap_id_TraceFailureIndication },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_38_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_CellTrafficTrace },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_39_S1ap_id_CellTrafficTrace },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_39_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_LocationReportingControl },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_40_S1ap_id_LocationReportingControl },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_40_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_LocationReportingFailureIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_41_S1ap_id_LocationReportingFailureIndication },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_41_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_LocationReport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_42_S1ap_id_LocationReport },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_42_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_OverloadStart },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_43_S1ap_id_OverloadStart },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_43_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_OverloadStop },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_44_S1ap_id_OverloadStop },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_44_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_ENBDirectInformationTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_45_S1ap_id_eNBDirectInformationTransfer },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_45_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_MMEDirectInformationTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_46_S1ap_id_MMEDirectInformationTransfer },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_46_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_ENBConfigurationTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_47_S1ap_id_eNBConfigurationTransfer },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_47_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_MMEConfigurationTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_48_S1ap_id_MMEConfigurationTransfer },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_48_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_PrivateMessage },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_49_S1ap_id_PrivateMessage },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_49_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_DownlinkUEAssociatedLPPaTransport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_50_S1ap_id_downlinkUEAssociatedLPPaTransport },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_50_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_UplinkUEAssociatedLPPaTransport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_51_S1ap_id_uplinkUEAssociatedLPPaTransport },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_51_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_DownlinkNonUEAssociatedLPPaTransport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_52_S1ap_id_downlinkNonUEAssociatedLPPaTransport },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_52_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_UplinkNonUEAssociatedLPPaTransport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_53_S1ap_id_uplinkNonUEAssociatedLPPaTransport },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_53_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_PWSRestartIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_54_S1ap_id_PWSRestartIndication },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_54_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_RerouteNASRequest },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_55_S1ap_id_RerouteNASRequest },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_55_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_PWSFailureIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_56_S1ap_id_PWSFailureIndication },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_56_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_ConnectionEstablishmentIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_57_S1ap_id_ConnectionEstablishmentIndication },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_57_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_NASDeliveryIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_58_S1ap_id_NASDeliveryIndication },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_58_S1ap_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_RetrieveUEInformation },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_59_S1ap_id_RetrieveUEInformation },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_59_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_UEInformationTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_60_S1ap_id_UEInformationTransfer },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_60_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_ENBCPRelocationIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_61_S1ap_id_eNBCPRelocationIndication },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_61_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_MMECPRelocationIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_62_S1ap_id_MMECPRelocationIndication },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_62_S1ap_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_S1ap_SecondaryRATDataUsageReport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_S1ap_ProcedureCode, &asn_VAL_63_S1ap_id_SecondaryRATDataUsageReport },
	{ "&criticality", aioc__value, &asn_DEF_S1ap_Criticality, &asn_VAL_63_S1ap_ignore }
};
static const asn_ioc_set_t asn_IOS_S1ap_S1AP_ELEMENTARY_PROCEDURES_1[] = {
	{ 63, 5, asn_IOS_S1ap_S1AP_ELEMENTARY_PROCEDURES_1_rows }
};
static int
memb_S1ap_procedureCode_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_SuccessfulOutcome_S1ap_criticality_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_S1ap_S1AP_ELEMENTARY_PROCEDURES_1;
	size_t constraining_column = 3; /* &procedureCode */
	size_t for_column = 4; /* &criticality */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct S1ap_SuccessfulOutcome, procedureCode));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_S1ap_criticality_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_type_selector_result_t
select_SuccessfulOutcome_S1ap_value_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_S1ap_S1AP_ELEMENTARY_PROCEDURES_1;
	size_t constraining_column = 3; /* &procedureCode */
	size_t for_column = 1; /* &SuccessfulOutcome */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct S1ap_SuccessfulOutcome, procedureCode));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_S1ap_value_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_oer_constraints_t asn_OER_memb_S1ap_procedureCode_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_per_constraints_t asn_PER_memb_S1ap_procedureCode_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_S1ap_criticality_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_memb_S1ap_criticality_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_S1ap_value_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_memb_S1ap_value_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_S1ap_value_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.HandoverCommand),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_HandoverCommand,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"HandoverCommand"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.HandoverRequestAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_HandoverRequestAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"HandoverRequestAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.PathSwitchRequestAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_PathSwitchRequestAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PathSwitchRequestAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.E_RABSetupResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_E_RABSetupResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"E-RABSetupResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.E_RABModifyResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_E_RABModifyResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"E-RABModifyResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.E_RABReleaseResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_E_RABReleaseResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"E-RABReleaseResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.InitialContextSetupResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_InitialContextSetupResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"InitialContextSetupResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.HandoverCancelAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_HandoverCancelAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"HandoverCancelAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.KillResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_KillResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"KillResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.ResetAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_ResetAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ResetAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.S1SetupResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_S1SetupResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"S1SetupResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.UEContextModificationResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_UEContextModificationResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"UEContextModificationResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.UEContextReleaseComplete),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_UEContextReleaseComplete,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"UEContextReleaseComplete"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.ENBConfigurationUpdateAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_ENBConfigurationUpdateAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ENBConfigurationUpdateAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.MMEConfigurationUpdateAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_MMEConfigurationUpdateAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"MMEConfigurationUpdateAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.WriteReplaceWarningResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_WriteReplaceWarningResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"WriteReplaceWarningResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.UERadioCapabilityMatchResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_UERadioCapabilityMatchResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"UERadioCapabilityMatchResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.E_RABModificationConfirm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_E_RABModificationConfirm,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"E-RABModificationConfirm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.UEContextModificationConfirm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_UEContextModificationConfirm,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"UEContextModificationConfirm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.UEContextSuspendResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_UEContextSuspendResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"UEContextSuspendResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome__value, choice.UEContextResumeResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_S1ap_UEContextResumeResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"UEContextResumeResponse"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_S1ap_value_tag2el_4[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 20 }, /* HandoverCommand */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 19 }, /* HandoverRequestAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -2, 18 }, /* PathSwitchRequestAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -3, 17 }, /* E-RABSetupResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -4, 16 }, /* E-RABModifyResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -5, 15 }, /* E-RABReleaseResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 6, -6, 14 }, /* InitialContextSetupResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 7, -7, 13 }, /* HandoverCancelAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 8, -8, 12 }, /* KillResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 9, -9, 11 }, /* ResetAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 10, -10, 10 }, /* S1SetupResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 11, -11, 9 }, /* UEContextModificationResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 12, -12, 8 }, /* UEContextReleaseComplete */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 13, -13, 7 }, /* ENBConfigurationUpdateAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 14, -14, 6 }, /* MMEConfigurationUpdateAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 15, -15, 5 }, /* WriteReplaceWarningResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 16, -16, 4 }, /* UERadioCapabilityMatchResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 17, -17, 3 }, /* E-RABModificationConfirm */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 18, -18, 2 }, /* UEContextModificationConfirm */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 19, -19, 1 }, /* UEContextSuspendResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 20, -20, 0 } /* UEContextResumeResponse */
};
static asn_CHOICE_specifics_t asn_SPC_S1ap_value_specs_4 = {
	sizeof(struct S1ap_SuccessfulOutcome__value),
	offsetof(struct S1ap_SuccessfulOutcome__value, _asn_ctx),
	offsetof(struct S1ap_SuccessfulOutcome__value, present),
	sizeof(((struct S1ap_SuccessfulOutcome__value *)0)->present),
	asn_MAP_S1ap_value_tag2el_4,
	21,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_S1ap_value_4 = {
	"value",
	"value",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	asn_MBR_S1ap_value_4,
	21,	/* Elements count */
	&asn_SPC_S1ap_value_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_S1ap_SuccessfulOutcome_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome, procedureCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_S1ap_ProcedureCode,
		0,
		{ &asn_OER_memb_S1ap_procedureCode_constr_2, &asn_PER_memb_S1ap_procedureCode_constr_2,  memb_S1ap_procedureCode_constraint_1 },
		0, 0, /* No default value */
		"procedureCode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome, criticality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_S1ap_Criticality,
		select_SuccessfulOutcome_S1ap_criticality_type,
		{ &asn_OER_memb_S1ap_criticality_constr_3, &asn_PER_memb_S1ap_criticality_constr_3,  memb_S1ap_criticality_constraint_1 },
		0, 0, /* No default value */
		"criticality"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct S1ap_SuccessfulOutcome, value),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_S1ap_value_4,
		select_SuccessfulOutcome_S1ap_value_type,
		{ &asn_OER_memb_S1ap_value_constr_4, &asn_PER_memb_S1ap_value_constr_4,  memb_S1ap_value_constraint_1 },
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_S1ap_SuccessfulOutcome_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_S1ap_SuccessfulOutcome_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* procedureCode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* criticality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_S1ap_SuccessfulOutcome_specs_1 = {
	sizeof(struct S1ap_SuccessfulOutcome),
	offsetof(struct S1ap_SuccessfulOutcome, _asn_ctx),
	asn_MAP_S1ap_SuccessfulOutcome_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_S1ap_SuccessfulOutcome = {
	"SuccessfulOutcome",
	"SuccessfulOutcome",
	&asn_OP_SEQUENCE,
	asn_DEF_S1ap_SuccessfulOutcome_tags_1,
	sizeof(asn_DEF_S1ap_SuccessfulOutcome_tags_1)
		/sizeof(asn_DEF_S1ap_SuccessfulOutcome_tags_1[0]), /* 1 */
	asn_DEF_S1ap_SuccessfulOutcome_tags_1,	/* Same as above */
	sizeof(asn_DEF_S1ap_SuccessfulOutcome_tags_1)
		/sizeof(asn_DEF_S1ap_SuccessfulOutcome_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_S1ap_SuccessfulOutcome_1,
	3,	/* Elements count */
	&asn_SPC_S1ap_SuccessfulOutcome_specs_1	/* Additional specs */
};

