/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Descriptions"
 * 	found in "/home/vagrant/magma/lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r15/s1ap-15.6.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-example -fno-include-deps -D /home/vagrant/build/c/core/oai/tasks/s1ap/r15`
 */

#ifndef	_S1ap_UnsuccessfulOutcome_H_
#define	_S1ap_UnsuccessfulOutcome_H_


#include <asn_application.h>

/* Including external dependencies */
#include "S1ap_ProcedureCode.h"
#include "S1ap_Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "S1ap_HandoverRequired.h"
#include "S1ap_HandoverCommand.h"
#include "S1ap_HandoverPreparationFailure.h"
#include "S1ap_HandoverRequest.h"
#include "S1ap_HandoverRequestAcknowledge.h"
#include "S1ap_HandoverFailure.h"
#include "S1ap_PathSwitchRequest.h"
#include "S1ap_PathSwitchRequestAcknowledge.h"
#include "S1ap_PathSwitchRequestFailure.h"
#include "S1ap_E-RABSetupRequest.h"
#include "S1ap_E-RABSetupResponse.h"
#include "S1ap_E-RABModifyRequest.h"
#include "S1ap_E-RABModifyResponse.h"
#include "S1ap_E-RABReleaseCommand.h"
#include "S1ap_E-RABReleaseResponse.h"
#include "S1ap_InitialContextSetupRequest.h"
#include "S1ap_InitialContextSetupResponse.h"
#include "S1ap_InitialContextSetupFailure.h"
#include "S1ap_HandoverCancel.h"
#include "S1ap_HandoverCancelAcknowledge.h"
#include "S1ap_KillRequest.h"
#include "S1ap_KillResponse.h"
#include "S1ap_Reset.h"
#include "S1ap_ResetAcknowledge.h"
#include "S1ap_S1SetupRequest.h"
#include "S1ap_S1SetupResponse.h"
#include "S1ap_S1SetupFailure.h"
#include "S1ap_UEContextModificationRequest.h"
#include "S1ap_UEContextModificationResponse.h"
#include "S1ap_UEContextModificationFailure.h"
#include "S1ap_UEContextReleaseCommand.h"
#include "S1ap_UEContextReleaseComplete.h"
#include "S1ap_ENBConfigurationUpdate.h"
#include "S1ap_ENBConfigurationUpdateAcknowledge.h"
#include "S1ap_ENBConfigurationUpdateFailure.h"
#include "S1ap_MMEConfigurationUpdate.h"
#include "S1ap_MMEConfigurationUpdateAcknowledge.h"
#include "S1ap_MMEConfigurationUpdateFailure.h"
#include "S1ap_WriteReplaceWarningRequest.h"
#include "S1ap_WriteReplaceWarningResponse.h"
#include "S1ap_UERadioCapabilityMatchRequest.h"
#include "S1ap_UERadioCapabilityMatchResponse.h"
#include "S1ap_E-RABModificationIndication.h"
#include "S1ap_E-RABModificationConfirm.h"
#include "S1ap_UEContextModificationIndication.h"
#include "S1ap_UEContextModificationConfirm.h"
#include "S1ap_UEContextSuspendRequest.h"
#include "S1ap_UEContextSuspendResponse.h"
#include "S1ap_UEContextResumeRequest.h"
#include "S1ap_UEContextResumeResponse.h"
#include "S1ap_UEContextResumeFailure.h"
#include "S1ap_HandoverNotify.h"
#include "S1ap_E-RABReleaseIndication.h"
#include "S1ap_Paging.h"
#include "S1ap_DownlinkNASTransport.h"
#include "S1ap_InitialUEMessage.h"
#include "S1ap_UplinkNASTransport.h"
#include "S1ap_ErrorIndication.h"
#include "S1ap_NASNonDeliveryIndication.h"
#include "S1ap_UEContextReleaseRequest.h"
#include "S1ap_DownlinkS1cdma2000tunnelling.h"
#include "S1ap_UplinkS1cdma2000tunnelling.h"
#include "S1ap_UECapabilityInfoIndication.h"
#include "S1ap_ENBStatusTransfer.h"
#include "S1ap_MMEStatusTransfer.h"
#include "S1ap_DeactivateTrace.h"
#include "S1ap_TraceStart.h"
#include "S1ap_TraceFailureIndication.h"
#include "S1ap_CellTrafficTrace.h"
#include "S1ap_LocationReportingControl.h"
#include "S1ap_LocationReportingFailureIndication.h"
#include "S1ap_LocationReport.h"
#include "S1ap_OverloadStart.h"
#include "S1ap_OverloadStop.h"
#include "S1ap_ENBDirectInformationTransfer.h"
#include "S1ap_MMEDirectInformationTransfer.h"
#include "S1ap_ENBConfigurationTransfer.h"
#include "S1ap_MMEConfigurationTransfer.h"
#include "S1ap_PrivateMessage.h"
#include "S1ap_DownlinkUEAssociatedLPPaTransport.h"
#include "S1ap_UplinkUEAssociatedLPPaTransport.h"
#include "S1ap_DownlinkNonUEAssociatedLPPaTransport.h"
#include "S1ap_UplinkNonUEAssociatedLPPaTransport.h"
#include "S1ap_PWSRestartIndication.h"
#include "S1ap_RerouteNASRequest.h"
#include "S1ap_PWSFailureIndication.h"
#include "S1ap_ConnectionEstablishmentIndication.h"
#include "S1ap_NASDeliveryIndication.h"
#include "S1ap_RetrieveUEInformation.h"
#include "S1ap_UEInformationTransfer.h"
#include "S1ap_ENBCPRelocationIndication.h"
#include "S1ap_MMECPRelocationIndication.h"
#include "S1ap_SecondaryRATDataUsageReport.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum S1ap_UnsuccessfulOutcome__value_PR {
	S1ap_UnsuccessfulOutcome__value_PR_NOTHING,	/* No components present */
	S1ap_UnsuccessfulOutcome__value_PR_HandoverPreparationFailure,
	S1ap_UnsuccessfulOutcome__value_PR_HandoverFailure,
	S1ap_UnsuccessfulOutcome__value_PR_PathSwitchRequestFailure,
	S1ap_UnsuccessfulOutcome__value_PR_InitialContextSetupFailure,
	S1ap_UnsuccessfulOutcome__value_PR_S1SetupFailure,
	S1ap_UnsuccessfulOutcome__value_PR_UEContextModificationFailure,
	S1ap_UnsuccessfulOutcome__value_PR_ENBConfigurationUpdateFailure,
	S1ap_UnsuccessfulOutcome__value_PR_MMEConfigurationUpdateFailure,
	S1ap_UnsuccessfulOutcome__value_PR_UEContextResumeFailure
} S1ap_UnsuccessfulOutcome__value_PR;

/* S1ap_UnsuccessfulOutcome */
typedef struct S1ap_UnsuccessfulOutcome {
	S1ap_ProcedureCode_t	 procedureCode;
	S1ap_Criticality_t	 criticality;
	struct S1ap_UnsuccessfulOutcome__value {
		S1ap_UnsuccessfulOutcome__value_PR present;
		union S1ap_UnsuccessfulOutcome__S1ap_value_u {
			S1ap_HandoverPreparationFailure_t	 HandoverPreparationFailure;
			S1ap_HandoverFailure_t	 HandoverFailure;
			S1ap_PathSwitchRequestFailure_t	 PathSwitchRequestFailure;
			S1ap_InitialContextSetupFailure_t	 InitialContextSetupFailure;
			S1ap_S1SetupFailure_t	 S1SetupFailure;
			S1ap_UEContextModificationFailure_t	 UEContextModificationFailure;
			S1ap_ENBConfigurationUpdateFailure_t	 ENBConfigurationUpdateFailure;
			S1ap_MMEConfigurationUpdateFailure_t	 MMEConfigurationUpdateFailure;
			S1ap_UEContextResumeFailure_t	 UEContextResumeFailure;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1ap_UnsuccessfulOutcome_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1ap_UnsuccessfulOutcome;
extern asn_SEQUENCE_specifics_t asn_SPC_S1ap_UnsuccessfulOutcome_specs_1;
extern asn_TYPE_member_t asn_MBR_S1ap_UnsuccessfulOutcome_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _S1ap_UnsuccessfulOutcome_H_ */
#include <asn_internal.h>
