/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SonTransfer-IEs"
 * 	found in "/home/vagrant/magma/lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r15/s1ap-15.6.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-example -fno-include-deps -D /home/vagrant/build/c/core/oai/tasks/s1ap/r15`
 */

#ifndef	_S1ap_ReportingCellList_H_
#define	_S1ap_ReportingCellList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct S1ap_ReportingCellList_Item;

/* S1ap_ReportingCellList */
typedef struct S1ap_ReportingCellList {
	A_SEQUENCE_OF(struct S1ap_ReportingCellList_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1ap_ReportingCellList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1ap_ReportingCellList;

#ifdef __cplusplus
}
#endif

#endif	/* _S1ap_ReportingCellList_H_ */
#include <asn_internal.h>
